services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./testing.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped